### ISSUE TITLE
Bug on batch destroy of associated records

### ISSUE THREAD

**Issue by jsurrett** [vhochstein/active_scaffold_batch#1]
When I open an associated list and then try to batch delete all listed records (the records associated with the parent), all the records in that model even the ones not listed are deleted.

Example: I have a list of families with line_items. If I list the line_items under the family and then choose batch -> destroy -> listed, all of the line items will be destroyed not just the ones listed for that family.

**Comment by vhochstein** [comment]
do you use process_mode delete_all?

**Comment by jsurrett** [comment]
I have not set conf.batch_destroy.process_mode = :delete_all on any of my controllers.

**Comment by vhochstein** [comment]
Hm, that s strange. I could reproduce your issue for :delete_all mode, however I could nt reproduce so far for "standard" mode.... Can you please try to debug?
