### ISSUE TITLE
Batch Create not working

### ISSUE THREAD

**Issue by guycall** [vhochstein/active_scaffold_batch#5]
Just upgraded a Rails 3.0 app using active_scaffold_batch_vho (3.0.6) & active_scaffold_vho (3.0.30) to Rails 3.1, active_scaffold_batch_vho (3.1.1) & active_scaffold_vho (3.1.6). The Batch Create has stopped working:

```
config.actions << :batch_base
config.actions.add :batch_create
config.batch_create.default_batch_by_column = :units
```

On the Rails 3.0 app this would give me a batch create form where the units select was set to 'multiple'. With the latest versions this just appears as a regular select.

**Comment by vhochstein** [comment]
hm... will have to take a look into it... Have you done a more in depth analysis already?

**Comment by guycall** [comment]
I created a frsh project and couldn't replicate the issue, so closing.
