### ISSUE TITLE
Rails 3.1/3.2?

### ISSUE THREAD

**Issue by jasonfb** [vhochstein/active_scaffold_batch#6]
is this still true?

Rails 3.1 Gem:
gem 'active_scaffold_config_batch'
or
gem 'active_scaffold_config_batch', :git => 'git://github.com/vhochstein/active_scaffold_batch.git'

when I try this on my Rails 3.2 app I get Could not find gem 'active_scaffold_config_batch (>= 0) ruby' in the gems available on this machine.

**Comment by vhochstein** [comment]
gem 'active_scaffold_batch_vho', :path => "/home/vhochstein/rails/projects/active_scaffold_batch"

I do not know of a active_scaffold_config_batch gem

**Comment by jasonfb** [comment]
It's in your README for this gem! 

Actually I couldn't get yours to work at all (was trying to mix it with active_scaffold 3.3.0.rc3 not active_scaffold_vho -- maybe that was my problem?)

I was able to get batch update to work using https://github.com/activescaffold/active_scaffold_batch, which looks like it got forked form this gem.

**Comment by jasonfb** [comment]
you may wish to update your README file, also it would be helpful to note if this gem requires you to use active_scaffold_vho or if one can use it against the mainline activescaffold/active_scaffold gem. 

closing issue now.
